### ISSUE TITLE
新抠图模型支持：birefnet-v1-lite

### ISSUE THREAD

**Issue by wanghkkk** [AIFSH/HivisionIDPhotos-ComfyUI#6]
官方更新了新的抠图模型：能否支持，谢谢
birefnet-v1-lite.onnx(224MB): [ZhengPeng7](https://github.com/ZhengPeng7/BiRefNet) 开源的抠图模型，[下载](https://github.com/ZhengPeng7/BiRefNet/releases/download/v1/BiRefNet-general-bb_swin_v1_tiny-epoch_232.onnx)后重命名为 birefnet-v1-lite.onnx

**Comment by AIFSH** [comment]
update，git pull
